; Inventory related enum values

; Constants
INVENTORY_SWORD equ $01
INVENTORY_BOMBS equ $02
INVENTORY_POWER_BRACELET equ $03
INVENTORY_SHIELD equ $04
INVENTORY_BOW equ $05
INVENTORY_HOOKSHOT equ $06
INVENTORY_MAGIC_ROD equ $07
INVENTORY_PEGASUS_BOOTS equ $08
INVENTORY_OCARINA equ $09
INVENTORY_ROCS_FEATHER equ $0A
INVENTORY_SHOVEL equ $0B
INVENTORY_MAGIC_POWDER equ $0C
INVENTORY_BOOMERANG equ $0D

INVENTORY_SLOT_COUNT equ $0C

CHEST_POWER_BRACELET_ID equ $00
CHEST_SHIELD_ID equ $01
CHEST_BOW_ID equ $02
CHEST_HOOKSHOT_ID equ $03
CHEST_MAGIC_ROD_ID equ $04
CHEST_PEGASUS_BOOTS_ID equ $05
CHEST_OCARINA_ID equ $06
CHEST_ROCS_FEATHER_ID equ $07
CHEST_SHOVEL_ID equ $08
CHEST_MAGIC_POWDER_ID equ $09
CHEST_BOMB_ID equ $0A
CHEST_SWORD_ID equ $0B
CHEST_FLIPPERS_ID equ $0C
CHEST_MAGNIFYING_LENS_ID equ $0D
CHEST_MEDICINE_ID equ $10

CHEST_TAIL_KEY_ID equ $11
CHEST_ANGLER_KEY_ID equ $12
CHEST_FACE_KEY_ID equ $13
CHEST_BIRD_KEY_ID equ $14

CHEST_MAP_ID equ $16
CHEST_COMPASS_ID equ $17
CHEST_STONE_BEAK_ID equ $18
CHEST_NIGHTMARE_KEY_ID equ $19
CHEST_SMALL_KEY_ID equ $1A

CHEST_50_RUPEES_ID equ $1B
CHEST_20_RUPEES_ID equ $1C
CHEST_100_RUPEES_ID equ $1D
CHEST_200_RUPEES_ID equ $1E
CHEST_200_RUPEES2_ID equ $1F
CHEST_SECRET_SEASHELL_ID equ $20

CHEST_MESSAGE_ID equ $21
CHEST_SLIME_ID equ $22